CREATE TABLE `owners` (
    `id` CHAR(36) PRIMARY KEY NOT NULL,
    `username` VARCHAR(50) UNIQUE NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `firstName` VARCHAR(255) NOT NULL,
    `lastName` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) UNIQUE NOT NULL,
    `dni` VARCHAR(255) UNIQUE NOT NULL,
    `ruc` VARCHAR(255) UNIQUE,
    `address` VARCHAR(100) NOT NULL,
    `phoneNumber` VARCHAR(30) UNIQUE NOT NULL,
    `role` ENUM('Manager', 'Admin') NOT NULL,
    `status` TINYINT(1) NOT NULL,
   -- `profilePictureUrl` TEXT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `createdBy` CHAR(36),
    `updatedBy` CHAR(36)
) ENGINE=InnoDB;

CREATE TABLE `customers` (
    `id` CHAR(36) PRIMARY KEY NOT NULL,
    `firstName` VARCHAR(100) NOT NULL,
    `lastName` VARCHAR(100) NOT NULL,
    `documentType` VARCHAR(30),
    `documentNumber` VARCHAR(30) UNIQUE NOT NULL,
    `email` VARCHAR(100) UNIQUE NOT NULL,
    `phoneNumber` VARCHAR(50) NULL,

    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE `products` (
    `id` CHAR(36) PRIMARY KEY NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    `description` TEXT,
    `stock` INT NOT NULL,
    `price` DECIMAL(10,2) NOT NULL,

    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE `orders` (
    `id` CHAR(36) PRIMARY KEY NOT NULL,
    `customerId` CHAR(36) NOT NULL,
    `totalPrice` DECIMAL(10,2),
    `status` ENUM('Pending', 'Processing','Completed', 'Cancelled') NOT NULL,
    
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`customerId`) REFERENCES `customers`(`id`) ON DELETE CASCADE,
) ENGINE=InnoDB;

CREATE TABLE `order_details` (
    `id` CHAR(36) PRIMARY KEY NOT NULL,
    `orderId` CHAR(36) NOT NULL,
    `productId` CHAR(36) NOT NULL,
    `quantity` INT NOT NULL,
    `unitPrice` DECIMAL(10,2) NOT NULL,
    `subtotal` DECIMAL(10,2) NOT NULL,

    FOREIGN KEY (`orderId`) REFERENCES `orders`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`productId`) REFERENCES `products`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB;